# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    async def ExtractMetadata(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DynamicMetadata:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExtractMetadata(text=text,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractMetadata", args={
                "text": text,
            })
            return typing.cast(types.DynamicMetadata, result.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateAnswer(self, context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Answer:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.GenerateAnswer(context=context,question=question,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateAnswer", args={
                "context": context,"question": question,
            })
            return typing.cast(types.Answer, result.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateFinanceBenchAnswer(self, context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.FinanceBenchAnswer:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.GenerateFinanceBenchAnswer(context=context,question=question,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateFinanceBenchAnswer", args={
                "context": context,"question": question,
            })
            return typing.cast(types.FinanceBenchAnswer, result.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateMedCaseReasoningAnswer(self, context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MedCaseReasoningAnswer:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.GenerateMedCaseReasoningAnswer(context=context,question=question,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateMedCaseReasoningAnswer", args={
                "context": context,"question": question,
            })
            return typing.cast(types.MedCaseReasoningAnswer, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractMetadata(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.DynamicMetadata, types.DynamicMetadata]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractMetadata", args={
            "text": text,
        })
        return baml_py.BamlStream[stream_types.DynamicMetadata, types.DynamicMetadata](
          result,
          lambda x: typing.cast(stream_types.DynamicMetadata, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DynamicMetadata, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GenerateAnswer(self, context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Answer, types.Answer]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateAnswer", args={
            "context": context,"question": question,
        })
        return baml_py.BamlStream[stream_types.Answer, types.Answer](
          result,
          lambda x: typing.cast(stream_types.Answer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Answer, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GenerateFinanceBenchAnswer(self, context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.FinanceBenchAnswer, types.FinanceBenchAnswer]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateFinanceBenchAnswer", args={
            "context": context,"question": question,
        })
        return baml_py.BamlStream[stream_types.FinanceBenchAnswer, types.FinanceBenchAnswer](
          result,
          lambda x: typing.cast(stream_types.FinanceBenchAnswer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FinanceBenchAnswer, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GenerateMedCaseReasoningAnswer(self, context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.MedCaseReasoningAnswer, types.MedCaseReasoningAnswer]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateMedCaseReasoningAnswer", args={
            "context": context,"question": question,
        })
        return baml_py.BamlStream[stream_types.MedCaseReasoningAnswer, types.MedCaseReasoningAnswer](
          result,
          lambda x: typing.cast(stream_types.MedCaseReasoningAnswer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MedCaseReasoningAnswer, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ExtractMetadata(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractMetadata", args={
            "text": text,
        }, mode="request")
        return result
    async def GenerateAnswer(self, context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateAnswer", args={
            "context": context,"question": question,
        }, mode="request")
        return result
    async def GenerateFinanceBenchAnswer(self, context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateFinanceBenchAnswer", args={
            "context": context,"question": question,
        }, mode="request")
        return result
    async def GenerateMedCaseReasoningAnswer(self, context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateMedCaseReasoningAnswer", args={
            "context": context,"question": question,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ExtractMetadata(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractMetadata", args={
            "text": text,
        }, mode="stream")
        return result
    async def GenerateAnswer(self, context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateAnswer", args={
            "context": context,"question": question,
        }, mode="stream")
        return result
    async def GenerateFinanceBenchAnswer(self, context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateFinanceBenchAnswer", args={
            "context": context,"question": question,
        }, mode="stream")
        return result
    async def GenerateMedCaseReasoningAnswer(self, context: str,question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateMedCaseReasoningAnswer", args={
            "context": context,"question": question,
        }, mode="stream")
        return result
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))