# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "clients.baml": "// Retry Policy for the clients\nretry_policy Exponential {\n  max_retries 2\n  strategy {\n    type exponential_backoff\n    delay_ms 300\n    multiplier 1.5\n    max_delay_ms 10000\n  }\n}\n\nclient<llm> GroqClient {\n  provider openai-generic\n  retry_policy Exponential\n  options {\n    base_url \"https://api.groq.com/openai/v1\"\n    api_key env.GROQ_API_KEY\n    model \"qwen/qwen3-32b\"\n    temperature 0.6\n    max_tokens 4096\n    top_p 0.95\n  }\n}\n\nclient<llm> CerebrasClient {\n  provider \"openai-generic\"\n  retry_policy Exponential\n  options {\n    base_url \"https://api.cerebras.ai/v1\"\n    api_key env.CEREBRAS_API_KEY\n    model \"qwen-3-32b\"\n    temperature 0.6\n    max_tokens 4096\n    top_p 0.95\n  }\n}\n\nclient<llm> SambaNovaClient {\n  provider \"openai-generic\"\n  retry_policy Exponential\n  options {\n    base_url \"https://api.sambanova.ai/v1\"\n    api_key env.SAMBANOVA_API_KEY\n    model \"qwen-3-32b\"\n    temperature 0.6\n    max_tokens 4096\n    top_p 0.95\n  }\n}\n\n\n// Fallback Client - Tries Groq, then Cerebras, then SambaNova\nclient<llm> GroqFallbackClient {\n  provider fallback\n  options {\n    // This will try the clients in order until one succeeds\n    // If Groq fails, try Cerebras, then SambaNova\n    strategy [GroqClient, CerebrasClient, SambaNovaClient]\n  }\n}\n\n",
    "generators.baml": "generator target {\n    output_type \"python/pydantic\"\n\n    // Where the generated code will be saved (relative to baml_src/)\n    output_dir \"../\"\n\n    // The version of the BAML package you have installed (e.g. same version as your baml-py or @boundaryml/baml).\n    // The BAML VSCode extension version should also match this version.\n    version \"0.214.0\"\n\n    // Valid values: \"sync\", \"async\"\n    // This controls what `b.FunctionName()` will be (sync or async).\n    default_client_mode async\n}\n",
}

def get_baml_files():
    return _file_map