# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractMetadata(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DynamicMetadata:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractMetadata", llm_response=llm_response, mode="request")
        return typing.cast(types.DynamicMetadata, result)

    def GenerateAnswer(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Answer:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateAnswer", llm_response=llm_response, mode="request")
        return typing.cast(types.Answer, result)

    def GenerateFinanceBenchAnswer(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.FinanceBenchAnswer:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateFinanceBenchAnswer", llm_response=llm_response, mode="request")
        return typing.cast(types.FinanceBenchAnswer, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractMetadata(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DynamicMetadata:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractMetadata", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DynamicMetadata, result)

    def GenerateAnswer(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Answer:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateAnswer", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Answer, result)

    def GenerateFinanceBenchAnswer(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.FinanceBenchAnswer:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateFinanceBenchAnswer", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.FinanceBenchAnswer, result)

    