# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (7)
# #########################################################################

class Answer(BaseModel):
    chain_of_thought: typing.Optional[str] = None
    summary: typing.Optional[str] = None

class DynamicMetadata(BaseModel):
    model_config = ConfigDict(extra='allow')

class FinanceBenchAnswer(BaseModel):
    chain_of_thought: typing.Optional[str] = None
    summary: typing.Optional[str] = None

class HealthBenchAnswer(BaseModel):
    chain_of_thought: typing.Optional[str] = None
    summary: typing.Optional[str] = None

class MedCaseReasoningAnswer(BaseModel):
    chain_of_thought: typing.Optional[str] = None
    diagnosis: typing.Optional[str] = None

class MetaMedQAAnswer(BaseModel):
    chain_of_thought: typing.Optional[str] = None
    answer: typing.Optional[str] = None

class PubMedAnswer(BaseModel):
    chain_of_thought: typing.Optional[str] = None
    answer: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
