# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Answer": types.Answer,
    "stream_types.Answer": stream_types.Answer,

    "types.DynamicMetadata": types.DynamicMetadata,
    "stream_types.DynamicMetadata": stream_types.DynamicMetadata,

    "types.FinanceBenchAnswer": types.FinanceBenchAnswer,
    "stream_types.FinanceBenchAnswer": stream_types.FinanceBenchAnswer,

    "types.MedCaseReasoningAnswer": types.MedCaseReasoningAnswer,
    "stream_types.MedCaseReasoningAnswer": stream_types.MedCaseReasoningAnswer,

    "types.MetaMedQAAnswer": types.MetaMedQAAnswer,
    "stream_types.MetaMedQAAnswer": stream_types.MetaMedQAAnswer,

    "types.PubMedAnswer": types.PubMedAnswer,
    "stream_types.PubMedAnswer": stream_types.PubMedAnswer,


}