# MetaMedQA Indexing Configuration

# Dataset configuration
dataset:
  path: "MedRAG/textbooks"
  split: "train"

# LLM configuration for metadata extraction
llm:
  model: "llama-3.3-70b-versatile"
  temperature: 0
  max_tokens: 1000
  max_retries: 3

# Embedding model
embedding:
  model_name: "Qwen/Qwen3-Embedding-0.6B"

# Milvus Vector Database settings
vectorstore:
  collection_name: "metamedqa"
  vector_fields: ["dense", "sparse"]
  consistency_level: "Strong"
  drop_old: true

# Unstructured Chunker configuration
chunking:
  chunking_strategy: "by_title"
  max_characters: 1000
  new_after_n_chars: 100
  overlap: 50
  overlap_all: true
  combine_text_under_n_chars: 100
  include_orig_elements: true
  multipage_sections: true

# Metadata schema for MetaMedQA
metadata_schema:
  properties:
    clinical_specialty:
      type: "string"
      description: "Medical specialty or department (e.g., cardiology, neurology, emergency medicine)"
    case_type:
      type: "string"
      description: "Type of clinical scenario (e.g., diagnostic, management, referral, triage)"
    patient_age:
      type: "string"
      description: "Patient age group or specific age if mentioned (e.g., '45-year-old', 'elderly', 'pediatric')"
    patient_gender:
      type: "string"
      description: "Patient gender (e.g., male, female, unspecified)"
    chief_complaint:
      type: "string"
      description: "Primary symptom or reason for encounter"

# Default value for missing metadata fields
metadata_defaults:
  default_value: "not specified"
